### ISSUE TITLE
Unable to bind to [shape] property of cds-icon component

### ISSUE THREAD

**Issue by conradbekondo** [vmware-clarity/ng-clarity#1535]
## Description of bug
Unable to bind values to the `[shape]` property of a `<cds-icon .../>` component in a template even while using the `ClrIconModule` as in the screenshot below

![image](https://github.com/user-attachments/assets/ed3d8208-58ba-4422-b46c-cb49a1c08369)

## How to reproduce

1. Add the `ClrIconModule` to the `imports` of a component
2. Place `<cds-icon ... />` tag and bind set its `share` property value using a binding (either `[share]` or `share="{{...}}"`) syntax
## Expected behavior

The code should be able to compile without errors.
## Versions

**Clarity version:**

- [ ] v13.x
- [ ] v15.x
- [x] Other:

**Framework version: *18.1.0*

**Device: *Windows - Ubuntu WSL*

- Type: DELL
- OS: Windows
- Browser: Chrome
- Version: 124

## Additional notes

Some icons don't get rendered as well. Check out the screenshot below.
![image](https://github.com/user-attachments/assets/dc48ef33-ad8b-4475-9d1e-fc2c44a073b3)

The green outlined icon was rendered properly while the red outlined icon wasn't. Am I using it wrong? Did I miss anything from the docs?

**Comment by kevinbuhmann** [comment]
You can use `[attr.shape]` to bind to the shape attribute. The `cds-icon` component is a web component and does not have Angular `@Input` properties.

In your last screenshot, the "avatar" icon is not rendering because the icon needs to be registered. Use `ClarityIcons.addIcons(avatarIcon)` to register the icon.

**Comment by kevinbuhmann** [comment]
You can use `[attr.shape]` to bind to the shape attribute. The `cds-icon` component is a web component and does not have Angular `@Input()` properties.

In your last screenshot, the "avatar" icon is not rendered because the icon needs to be registered. Use `ClarityIcons.addIcons(avatarIcon)` to register the icon. See here for an example: https://core.clarity.design/foundation/icons/

**Comment by LynxDelli** [comment]
https://stackblitz.com/edit/clarity-icons-binding?file=src%2Fapp%2Fapp.component.html I hope this stackblitz will help.

**Comment by conradbekondo** [comment]
> You can use `[attr.shape]` to bind to the shape attribute. The `cds-icon` component is a web component and does not have Angular `@Input()` properties.
> 
> In your last screenshot, the "avatar" icon is not rendered because the icon needs to be registered. Use `ClarityIcons.addIcons(avatarIcon)` to register the icon. See here for an example: https://core.clarity.design/foundation/icons/

Thanks so much. This solved the problem. Would be better not to have to call `ClarityIcons#addIcons` method tho

**Comment by kevinbuhmann** [comment]
> Thanks so much. This solved the problem.

Awesome. You're welcome!

> Would be better not to have to call `ClarityIcons#addIcons` method tho

I understand this can be cumbersome, but it is necessary so that only icons that are used are included in your application bundle.
