### ISSUE TITLE
datagrid: clr-dg-action-overflow button not focusable

### ISSUE THREAD

**Issue by oznu** [vmware-clarity/ng-clarity#1549]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support space in Google Chat to raise Clarity issues._**

## Describe the bug

The `clr-dg-action-overflow` button has a `tabindex="-1"` attribute so cannot be focused using tab

<img width="731" alt="image" src="https://github.com/user-attachments/assets/1c07a93b-282e-406a-8141-a0dec756d1c3">

https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/data/datagrid/datagrid-action-overflow.ts#L40

## How to reproduce

This is reproducible in the example provided in the docs:

https://clarity.design/documentation/datagrid/code/single-action

## Expected behaviour

The button should not have `tabindex="-1"` so keyboard only users can access actions button using `Tab`.

## Versions

**Clarity version:**

- [x ] v17.3.0

This was not an issue in v17.2.1.

**Framework version:**

Angular 18

**Comment by kevinbuhmann** [comment]
>The `clr-dg-action-overflow` button has a `tabindex="-1"` attribute so cannot be focused using tab.

This is intentional and not a bug. Keyboard navigation with a datagrid is via the arrow keys and page up/down. The tab key should move focus to the next interactive element _after_ the datagrid. (Note that this isn't always implemented automatically for interactive elements projected into a datagrid cell.)

For more information: https://www.w3.org/WAI/ARIA/apg/patterns/grid/

>A grid is a composite widget so it:
>- Always contains multiple focusable elements.
>- Only one of the focusable elements contained by the grid is included in the page tab sequence.

**Comment by kevinbuhmann** [comment]
>The `clr-dg-action-overflow` button has a `tabindex="-1"` attribute so cannot be focused using tab.

This is intentional and not a bug. Keyboard navigation within a datagrid is via the arrow keys and page up/down. The tab key should move focus to the next interactive element _after_ the datagrid. (Note that this isn't always implemented automatically for interactive elements projected into a datagrid cell.)

For more information: https://www.w3.org/WAI/ARIA/apg/patterns/grid/

>A grid is a composite widget so it:
>- Always contains multiple focusable elements.
>- Only one of the focusable elements contained by the grid is included in the page tab sequence.
