### ISSUE TITLE
Datepicker JS errors when screen width <768px on mobile device

### ISSUE THREAD

**Issue by runtothesun** [vmware-clarity/ng-clarity#310]
## Describe the bug

When loading a page with a date picker with screen width of <768px an error is raised in the console: 

Safari:
`TypeError: undefined is not an object (evaluating 'this.toggleButton.nativeElement')`

Chrome:
`ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')`

## How to reproduce

1. Open chrome, open dev tools. set screen dimensions to responsive and set width to 767px.
2. Open https://clarity.design/documentation/datepicker in chrome. 
3. View console logs

## Expected behavior

No errors should appear.

## Versions

**Clarity version:**

-  v12.x

**Framework:**

- Angular

**Framework version:**
Angular 12

**Device:**

- Type: any
- OS: iOS / windows / linux
- Browser: safari / chrome
- Version: 15.6.1 / latest

## Additional notes

I've updated the issue as it appears to be related to when the datepicker uses the native date control

I believe the issue was introduced by [this commit](https://github.com/vmware-clarity/ng-clarity/commit/11a75f605bcd0bf198086a52c0b05847f2555a85)

**Comment by bbogdanov** [comment]
FYI:

That's interesting, I'm using a chromium based browser (Brave) and I can't catch that error there.

**Comment by runtothesun** [comment]
I've just checked it again and it's definitely still throwing an error in Chroem when set to use a narrow screen:
![Screenshot from 2022-09-12 12-27-27](https://user-images.githubusercontent.com/52045847/189642337-7e6b1bf4-3f57-4116-ba22-9a12e165cfb6.png)

**Comment by ManuEtt** [comment]
Hallo, 

wir haben auch das gleiche Problem mit dem DatePicker.
Wir haben das auch auf verschiedenen Browser getestet, immer der selbe Fehler.

**Comment by qpfmtlcp** [comment]
I've the same problem too.
with clarity v13, angular v14

**Comment by juhand777** [comment]
Hi. is there a workaround for it?

![image](https://user-images.githubusercontent.com/392970/197483622-55e9576e-fd96-412e-b0e7-e70bc1212162.png)

Clarity 13.9.0
Angular 13.3.0

**Comment by Cyber1000** [comment]
any solutions to this? Having it with angular v15 and clarity v15-beta4 (I know it's a beta, but it's exactly the same error)

**Comment by Cyber1000** [comment]
@runtothesun you are right: the commit seemed to introduce this. Today the problem is here:
- https://github.com/vmware-clarity/ng-clarity/blob/0e4d931154846175df4bf6732bee1b2444f08593/projects/angular/src/forms/datepicker/date-container.ts#L207
- this.toggleButton is undefined, because of this ngif: https://github.com/vmware-clarity/ng-clarity/blob/0e4d931154846175df4bf6732bee1b2444f08593/projects/angular/src/forms/datepicker/date-container.ts#L46
- isenabled asks the datepickerEnabledService, this returns false if this: https://github.com/vmware-clarity/ng-clarity/blob/0e4d931154846175df4bf6732bee1b2444f08593/projects/angular/src/forms/datepicker/providers/datepicker-enabled.service.ts#L36
- DATEPICKER_ENABLE_BREAKPOINT is 768: https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/utils/breakpoints/breakpoints.ts

What I tried so far: somehow overwrite DATEPICKER_ENABLE_BREAKPOINT in worst case replace it in my node_modules before serving. No effort so far, maybe someone has another idea.

A fix by clarity-team would be the best option, it's clearly a bug after digging through sources.

**Comment by kevinbuhmann** [comment]
This fell through the cracks. Thanks for bringing it back up. I am looking into it now.

**Comment by Cyber1000** [comment]
@kevinbuhmann Wow that was fast 👍  , thanks, can we expect this to get into upcoming clarity v15? (don't know your merge process exactly)

**Comment by kevinbuhmann** [comment]
Yes, this fix will land in v13 and v15.
