### ISSUE TITLE
[Datagrid] Selection checkboxes are reported as having multiple labels

### ISSUE THREAD

**Issue by deyanovae** [vmware-clarity/ng-clarity#378]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

Multiple form labels in selection checkboxes: http://vtaas.eng.vmware.com:9003/document/accessibility/guideline/label_multiple.html

1.  Go to https://clarity.design/documentation/datagrid/selection.
2.  Scroll down to the example with row selection mode.
3.  Run WAVE tool.
4.  There are several errors related to multiple form labels.

![Multiple_form_labels](https://user-images.githubusercontent.com/117344526/199953554-96951607-672f-4a46-9394-24acbf613328.png)

## Expected behavior

Ensure that at most one label element is associated to the form control. If multiple form labels are necessary, use aria-labelledby.

## Versions

**Clarity version:**

- [ ] v12.x
- [ ] v13.x

**Framework:**

- [ ] Angular

**Framework version:**
Angular 12, 13

**Device:**

- Type: [e.g. MacBook]

**Comment by Jinnie** [comment]
I see where the problem is.
![Screen Shot 2022-11-21 at 10 05 56](https://user-images.githubusercontent.com/1798828/202997105-f89c919d-942c-4be4-a1aa-145fbf98a2d7.jpg)

We:
1) have a sr-only label at the input itself
2) have a label wrapping the whole row when row selection is enabled

This is another good example why the row-selection pattern is questionable (cc: @pdaigle )

We can try to fix it by conditionally removing the sr-only label when in row-selection. But this will require additional dev research to make sure it is achievable.
