### ISSUE TITLE
ClrCheckbox input is misaligned with its label

### ISSUE THREAD

**Issue by krnhotwings** [vmware-clarity/ng-clarity#440]
## Describe the bug

Clarity checkbox uses `label::before` to draw the box for the checkbox and `label::after` to draw the check mark. The actual `input` is invisible but rendered slightly upward from its center. If you click just above a clarity checkbox, this will allow interaction with the checkbox. Conversely, if you click inside the bottom area of the checkbox, it will *not* interact with the checkbox.

## How to reproduce

You can observe the behavior in the documentation:

https://clarity.design/documentation/checkboxes

Under the "Basic checkbox button" heading, there's a checkbox. Click above it and it will activate the checkbox. If you use developer tools to look at its input, you'll see that it's rendered off-center, above the drawn checkbox.

## Expected behavior

Clicking anywhere inside the checkbox should activate/deactivate the checkbox. Clicking outside the checkbox should do nothing.

I'm not too savvy with CSS, but it seems that setting `.clr-checkbox-wrapper input[type="checkbox"]`'s `top` attribute from `0.25rem` to `0.9rem` aligns things pretty nicely.

## Versions

**Clarity version:**

13.11.1

**Framework version:**

Angular 14.2.12

**Device:**

- Type: PC
- OS: Fedora 37
- Browser: Firefox
- Version: 107.0

**Comment by kevinbuhmann** [comment]
Thanks for this bug report!

I see the misalignment in dev tools on Firefox on macOS, but clicking anywhere inside the checkbox (or directly above it) toggles the checkbox which is slightly different than described. I may need to set up a Fedora VM. It appears perfectly aligned in Chrome, at least on macOS.

So this may be a bit difficult to solve since it's both browser- and OS-dependent, but we will see what we can do. The team is out for the rest of the year, so you probably won't hear any updates until January.

**Comment by krnhotwings** [comment]
Hmm, on Fedora 37, Chromium 108.0.5359.124, the clickable area of the checkbox seems to cover the entire checkbox + a small area above the checkbox.

**Comment by kevinbuhmann** [comment]
That extra label height in Firefox may be "pushing" the `input` element up? I'm not sure, but it could related. So thanks for this discovery!

**Comment by dtsanevmw** [comment]
Closing due to not supported version and seems that is not reproducible in current supported versions.
