### ISSUE TITLE
Border disappears in button group with disabled button

### ISSUE THREAD

**Issue by Sadderp** [vmware-clarity/ng-clarity#915]
## Describe the bug

The border between the buttons in a button group disappears when the first button is disabled

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-ng14-pnqh9j?file=src%2Fapp%2Fapp.component.html

1. Wait for the file to load
2. See error

## Expected behavior

The border should be visible even when the first button is disabled.

## Versions

**Clarity version:**

- [ ] v13.x
- [x] v15.x
- [ ] Other:

**Framework version:**
Angular v.14.2.10

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Firefox
- Version: 116.0.3

**Comment by pawaru** [comment]
This happens because of the selector:
```
    .btn + .btn {
      border-left: none;
    }
```
specified [here](https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/button/button-group/_button-group.clarity.scss#L144): 


The left borders are removed for 2nd button onwards to avoid double borders.
Hence for every disabled button followed by an enabled button on the right, will not have the border separating the 2 buttons.
