### ISSUE TITLE
Clarity Documentation: Alerts, icon usage outdated

### ISSUE THREAD

**Issue by d-m-s** [vmware-clarity/ng-clarity#967]
## Describe the bug
Caret down icons in the alert example missing in documentation. 

## How to reproduce

1.  Go to https://clarity.design/documentation/alerts#examples
2.  See examples, inside the alert examples on the right.
3.  See error: "..." icon spinning.
<img width="617" alt="2023-09-26_10h54_21" src="https://github.com/vmware-clarity/ng-clarity/assets/311619/0347c9cd-f8f7-4683-ac90-a39e53cbd1c6">

## Expected behavior
Caret-down icon shown.
Click on link/icon should reveal further actions.
Correct code example below.

## Versions
**Clarity version:** v15
**Framework version:** Angular 15
**Device:** Any

**Comment by kevinbuhmann** [comment]
This will be fixed tomorrow when we release our v16 website.

**Comment by d-m-s** [comment]
Icons are fixed, but its not a working example anymore.
Click on link "Actions" does not reveal the actions.

Issue could be closed, or further improved.

**Comment by kevinbuhmann** [comment]
This particular example was static previously as well. See https://v15.clarity.design/documentation/alerts.

The CSS-only examples are all static. We don't include the JS code needed make them functional because we are just demonstrating the CSS/HTML shown in the code snippets.

There is a functional example further down the page that uses the `clr-alert` component.
